### ISSUE TITLE
writes don't work in node

### ISSUE THREAD

**Issue by fcheslack** [fcheslack/libZoteroJS#11]
Trying to do an item write in node causes an error from w3c-xmlhttprequest:

>/libzoterojs/node_modules/w3c-xmlhttprequest/lib/xmlhttprequest.js:129
>      lengthComputable: _properties.lengthComputable,
>                                   ^
>
>TypeError: Cannot read property 'lengthComputable' of undefined
>    at TLSSocket.stream.on (/home/fcheslack/Dev/libzoterojs/node_modules/w3c-xmlhttprequest/lib/xmlhttprequest.js:129:36)
>    at emitOne (events.js:101:20)
>    at TLSSocket.emit (events.js:188:7)
>    at readableAddChunk (_stream_readable.js:177:18)
>    at TLSSocket.Readable.push (_stream_readable.js:135:10)
>    at TLSWrap.onread (net.js:542:20)

**Comment by fcheslack** [comment]
https://github.com/ykzts/node-xmlhttprequest/issues/40

**Comment by fcheslack** [comment]
resolved with https://github.com/fcheslack/libZoteroJS/issues/12
